export const REQUEST_WORKERS_WATCHER = 'REQUEST_WORKERS_WATCHER';
export const REQUEST_WORKERS = 'REQUEST_WORKERS';
export const IS_REQUESTING = 'IS_REQUESTING';
export const UPDATE_WORKERS = 'UPDATE_WORKERS';
export const UPDATE_WORKERS_WATCHER = 'UPDATE_WORKERS_WATCHER';
export const RESET_LIST = 'RESET_LIST';
